# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B94f_FfsOfpilORGVK-K_yzHkqlFZHUF
"""

import math

def scientific_calculator():
    print("Scientific Calculator")
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Power (x^y)")
    print("6. Square Root")
    print("7. Logarithm (base 10)")
    print("8. Natural Logarithm (ln)")
    print("9. Sine")
    print("10. Cosine")
    print("11. Tangent")

    choice = input("Enter choice (1-11): ")

    if choice in ['1','2','3','4','5']:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print(f"{num1} + {num2} = {num1 + num2}")
        elif choice == '2':
            print(f"{num1} - {num2} = {num1 - num2}")
        elif choice == '3':
            print(f"{num1} * {num2} = {num1 * num2}")
        elif choice == '4':
            if num2 != 0:
                print(f"{num1} / {num2} = {num1 / num2}")
            else:
                print("Error! Division by zero.")
        elif choice == '5':
            print(f"{num1}^{num2} = {math.pow(num1, num2)}")

    elif choice in ['6','7','8','9','10','11']:
        num = float(input("Enter number: "))

        if choice == '6':
            print(f"√{num} = {math.sqrt(num)}")
        elif choice == '7':
            print(f"log10({num}) = {math.log10(num)}")
        elif choice == '8':
            print(f"ln({num}) = {math.log(num)}")
        elif choice == '9':
            print(f"sin({num}) = {math.sin(math.radians(num))}")
        elif choice == '10':
            print(f"cos({num}) = {math.cos(math.radians(num))}")
        elif choice == '11':
            print(f"tan({num}) = {math.tan(math.radians(num))}")

    else:
        print("Invalid input")

scientific_calculator()