# -*- coding: utf-8 -*-
"""password.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWTTJbBFdMaao21CnhWhU4SectoyQvJf
"""

import random
import string

def generate_password(length=12):
    # Define possible characters
    characters = string.ascii_letters + string.digits + string.punctuation

    # Generate password
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

# Example usage
length = int(input("Enter password length: "))
print("Generated Password:", generate_password(length))