# -*- coding: utf-8 -*-
"""rock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiq4G0_5adTEld7jsuwCJxHCmORJJpLK
"""

import random

def play():
    print("Rock-Paper-Scissors Game")
    print("Choices: rock, paper, scissors")

    user_choice = input("Enter your choice: ").lower()
    options = ["rock", "paper", "scissors"]
    computer_choice = random.choice(options)

    print(f"You chose: {user_choice}")
    print(f"Computer chose: {computer_choice}")

    if user_choice == computer_choice:
        print("It's a tie!")
    elif user_choice == "rock":
        if computer_choice == "scissors":
            print("You win! Rock crushes scissors.")
        else:
            print("You lose! Paper covers rock.")
    elif user_choice == "paper":
        if computer_choice == "rock":
            print("You win! Paper covers rock.")
        else:
            print("You lose! Scissors cut paper.")
    elif user_choice == "scissors":
        if computer_choice == "paper":
            print("You win! Scissors cut paper.")
        else:
            print("You lose! Rock crushes scissors.")
    else:
        print("Invalid choice. Please select rock, paper, or scissors.")

play()